config/routes.rb
Rails.application.routes.draw do

  apipie
  resources :addresses

  resources :messages

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  scope "(:locale)" do
    resources :private_messages
    get "support_contact" => "private_messages#support_contact"
    post "message_support_contact" => "private_messages#message_support_contact"
    get "reply" => "private_messages#reply"
    get "trash" => "private_messages#trash"
    get "untrash" => "private_messages#untrash"
    get "show_pgp" => "private_messages#show_pgp"
    get "show_sender_detail" => "private_messages#show_sender_detail"
    get "read_conversation" => "private_messages#read_conversation"
    get "unread_conversation" => "private_messages#unread_conversation"
    get "trash_private_message" => "private_messages#trash_private_message"
    get "untrash_private_message" => "private_messages#untrash_private_message"
    get "read_private_message" => "private_messages#read_private_message"
    get "unread_private_message" => "private_messages#unread_private_message"
    
    resources :orders do 
      post "confirm_order" => "orders#confirm_order"
      get "shipped_order" => "orders#shipped_order"
      post "request_buyer_attention_order" => "orders#request_buyer_attention_order"
      post "partially_shipped_order" => "orders#partially_shipped_order"
      get "cancel_order" => "orders#cancel"
    end
    
    get "auth_payment" => "orders#auth_payment" 
    post "finalize_order" => "orders#finalize_order"
    post "sent_order" => "orders#sent_order"
    get "orders/details/:id" => "orders#order_detail", as: :order_detail
    get "order_list" => "orders#order_list", as: :orders_list
    get "waiting_list" => "orders#waiting_list", as: :waiting_list
    get "approve_and_sent_orders" => "orders#approve_and_sent_orders", as: :approve_and_sent_orders
    post "pay" => "orders#pay", as: :pay
    get "pay_order_in_order" => "orders#pay_order_in_order", as: :pay_order_in_order
    get "pay_multisig" => "orders#pay_multisig"
    get "account_btc" => "orders#account", as: :bitcoin_account
    post "withdraw_funds" => "orders#withdraw_funds"
    post "transfer_fund" => "orders#transfer_fund"
    get "member" => "orders#member"
    get "create_new_bitcoin_address" => "orders#create_new_bitcoin_address", as: :create_new_bitcoin_address
    get "form_refund" => "orders#form_refund"
    post "refund_order" => "orders#refund_order", as: :refund_order
    get "validate_wallet" => "orders#validate_wallet", as: :validate_wallet
    get "pay_if_fund_not_enough" => "orders#pay_if_fund_not_enough", as: :pay_if_fund_not_enough

    resources :items, except: [:destroy]
    get "destroy_item" => "items#destroy"
    get "destroy_shipping_option" => "items#destroy_shipping_option"
    get "confirm_delete" => "items#confirm_delete", as: :confirm_delete
    get "copy_item" => "items#copy_item", as: :copy_item
    get "change_status" => "items#change_status", as: :change_status
    get "shipping_option/new" => "items#shipping_option_new"
    post "shipping_options" => "items#create_shpping_option_new"
    get "shipping_option_list" => "items#shipping_option_list", as: :shipping_option_list
    get "shipping_option/:id/edit" => "items#shipping_option_edit", as: :shipping_option_edit
    patch "shipping_option/:id" => "items#update_shipping_options", as: :shipping_option
    get "vendor_item" => "items#vendor_item"

    resources :categories
    resource :shopping_cart
    get "delete_cart/:id" => "shopping_carts#delete_cart", as: :delete_cart
    post "shopping_carts/encrypt_shipping_information"
    post "shopping_carts/pay_page"
    get "pay_order" => "shopping_carts#pay_order", as: :pay_order
    get "create_multi_sig" => "shopping_carts#create_multi_sig"
    post "shopping_carts/generate_multi_sig"
    get "pay_qr" => "shopping_cart#pay_qr", as: :pay_qr

    devise_scope :user do
      get 'users/vendor_sign_up', to: 'users/registrations#vendor_sign_up', as: 'vendor_sign_up'
      get ":token/register", to: "users/registrations#new"
    end
    devise_for :users, :controllers => { :registrations => "users/registrations", :sessions => "users/sessions" }
    resources :conversations, only: [:index, :show, :new, :create] do
      collection do
        get :inbox
        get :sentbox
        get :trash_list
      end
      member do
        post :reply
        post :trash
        post :untrash
      end
    end
    get "uncategories_items" => "dashboard#uncategories_items", as: :uncategories_items
    get "item_search" => "dashboard#item_search", as: :item_search
    get "category/:id" => "dashboard#item_by_category", as: :item_by_category
    get "dashboard" => "dashboard#dashboard", as: :dashboard
    post "dashboard" => "dashboard#dashboard", as: :dashboard_post
    get "dashboard_vendor" => "dashboard#dashboard_vendor", as: :dashboard_vendor
    post "dashboard_vendor" => "dashboard#dashboard_vendor", as: :dashboard_vendor_post
    get "list_country" => "dashboard#list_country"
    get "show_item_by_country" => "dashboard#show_item_by_country"
    get "item-detail/:random_string" => "dashboard#item_detail", as: :item_detail
    get "account" => "dashboard#show_buyer", as: :buyer_account
    get "show_full_image/:random_string" => "dashboard#show_full_image", as: :show_full_image
    get "upload-pgp-key" => "pgp#upload_key"
    post "pgp/check_pgp_key"
    get "input_string" => "pgp#input_string"
    get "input_string_from_profile" => "pgp#input_string_from_profile" 
    get "input_string_first_time" => "pgp#input_string_first_time" 
    get "confirmation_change_password" => "pgp#confirmation_change_password"
    get "change_password" => "pgp#change_password"
    post "pgp/check_random_string"
    post "pgp/check_random_string_from_profile"
    post "pgp/check_random_string_first_time"
    post "pgp/confirm_new_password"
    get "history" => "history#index", as: :history
    get "home" => "home#index"
    get "invite_new_buyer" => "invites#invite_new_buyer"
    get "invites/cancel_invited"
    post "invites/sent_invitation"
    get "new_wallet" => "blockchain#new_wallet"
    post "blockchain/create_new_wallet"
    # get '*path' => redirect("/")

    root 'home#index'
  end

  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'login' => 'sessions#create', as: 'login'
        delete 'logout' => 'sessions#destroy', as: 'logout'
      end
      get "dashboard" => "dashboard#dashboard"
      get "dashboard_vendor" => "dashboard#dashboard_vendor"
      get "category/:id" => "dashboard#item_by_category", as: :item_by_category
      get "account" => "dashboard#show_buyer", as: :buyer_account
      get "item-detail/:id" => "dashboard#item_detail"

      get "categories" => "categories#index"

      get "shipping_options" => "shipping_options#index"
      get "shipping_options/:id/edit" => "shipping_options#edit"
      post "shipping_options/:id" => "shipping_options#update"
      post "create_shipping_option" => "shipping_options#create"

      get "countries" => "countries#index"
      get "ship_from" => "countries#ship_from"
      get "ship_to" => "countries#ship_to"

      get "currencies" => "currency_config#index"

      post "create_user" => "users#create"
      get "users/:id/edit" => "users#edit"
      post "users/:id" => "users#update"

      get "messages" => "messages#index"
      get "list_recipient" => "messages#list_recipient"
      get "create_message" => "messages#create_message"
      post "sent_message" => "messages#sent_message"
      get "reply" => "messages#reply"
      get "support_contact" => "messages#support_contact"
      post "message_support_contact" => "messages#message_support_contact"

      get "items" => "items#index"
      get "copy_item" => "items#copy_item"
      get "change_status" => "items#change_status"
      get "destroy_item" => "items#destroy"
      get "items/:id/edit" => "items#edit"
      post "items/:id" => "items#update"
      post "create_item" => "items#create"

      get "order_list" => "orders#order_list"
      get "orders" => "orders#index"
      get "orders/:order_id/shipped_order" => "orders#shipped_order"
      post "sent_order" => "orders#sent_order"
      get "form_refund" => "orders#form_refund"
      post "refund_order" => "orders#refund_order"
      post "finalize_order" => "orders#finalize_order"
      get "account_btc" => "orders#account"
      get "create_new_bitcoin_address" => "orders#create_new_bitcoin_address"
      get "member" => "orders#member"
      post "withdraw_funds" => "orders#withdraw_funds"
      post "transfer_fund" => "orders#transfer_fund"
      get "pay_order_in_order" => "orders#pay_order_in_order"

      post "shopping_cart" => "shopping_carts#create"
      post "shopping_carts/update_order"
      get "shopping_cart" => "shopping_carts#show"
      post "shopping_carts/message_information"
      get "pay" => "shopping_carts#pay"
      post '/delete_cart/:id' => "shopping_carts#delete_cart"
    end  
  end
end

app/controllers/api/v1/dashboard_controller.rb
class Api::V1::DashboardController < ApiController
  impressionist :actions => [:item_detail]

  def_param_group :search_item_for_vendor do
    param :search_item_for_vendor, Hash, desc: "Parameters for do search in vendor dashboard." do
      param :limit, String, desc: "Limit of show item in dashboard"
      param :hours, String, desc: "Show item by activity vendor"
      param :fe, String, desc: "Show item by Fe policy"
      param :sort, String, desc: "Show item by order "
      param :ship_to, String, desc: "Show item by ship to"
      param :ship_from, String, desc: "Show item by ship from"
      param :ship_from, String, desc: "Show item by ship from"
      param :rating, String, desc: "Show item by vendor vendor"
      param :member, String, desc: "Show item by vendor is member or not"
      param :name, String, desc: "Show item by name"
    end
  end

  def_param_group :search_item_for_buyer do
    param :search_item_for_buyer, Hash, desc: "Parameters for do search in buyer dashboard." do
      param :limit, String, desc: "Limit of show item in dashboard"
      param :hours, String, desc: "Show item by activity vendor"
      param :fe, String, desc: "Show item by Fe policy"
      param :sort, String, desc: "Show item by order "
      param :ship_to, String, desc: "Show item by ship to"
      param :ship_from, String, desc: "Show item by ship from"
      param :ship_from, String, desc: "Show item by ship from"
      param :rating, String, desc: "Show item by vendor vendor"
      param :member, String, desc: "Show item by vendor is member or not"
      param :name, String, desc: "Show item by name"
    end
  end

  api :GET, '/v1/dashboard', 'Dashboad Buyer'
  param_group :search_item_for_buyer
  def dashboard
    @items = Item.get_filtered_items_for_buyer(params)
    render "/v1/dashboard/dashboard"
  end

  api :GET, '/v1/dashboard_vendor', 'Dashboad Vendor'
  param_group :search_item_for_vendor
  def dashboard_vendor
    @items = Item.get_filtered_items_for_vendor(params)
    render "api/v1/dashboard/dashboard_vendor"
  end
  
  api :GET, '/v1/countries/:id', 'Show item by category'
  param :id, Integer, desc: "Category Id", required: true
  def item_by_category
    category = Category.find(params[:id])
    @category_items = category.items
    render "api/v1/dashboard/item_by_category"
  end

  api :GET, '/v1/account', 'Show detail of user'
  param :auth_token, String, desc: "Authentication Token User", required: true
  def show_buyer
    @user = User.where(authentication_token: params[:auth_token]).first
    @bitcoin_address = @user.addresses.where(is_active: true).first.address
    @bitcoin_balance = `bitcoin-cli getbalance #{@user.username}`
    check_pgp = File.exist? [Rails.root, "/public/pgp/users/#{@user.id}/publickey.asc"].join
    if check_pgp.eql? true
      file = File.open("public/pgp/users/#{@user.id}/publickey.asc")
      @publickey = file.read
    end
    render "api/v1/dashboard/show_buyer"
  end

  api :GET, '/v1/item_detail/:id', 'Show detail of item for buyer'
  param :id, String, desc: "Id of item", required: true
  def item_detail
    @item = Item.find(params[:id])
    category = @item.categories.first
    item = Item.where(id: params[:id])
    if category.present?
      @related_items = category.items - item
    end
    @shippings = @item.user.shipping_options.collect{ |shipping_option| ["#{shipping_option.name} (#{shipping_option.price} #{shipping_option.currency})", shipping_option.id]}
    if current_user.role.eql?"Buyer"
      impressionist(@item)
    end
    render "api/v1/dashboard/item_detail"
  end

end

app/controllers/dashboard_controller.rb
require 'httparty'
class DashboardController < ApplicationController
  impressionist actions: [:index]
  before_action :authenticate_user!
  before_action :category
  before_action :seventy_two_hours_ago, only: [:item_by_category, :uncategories_items]
  impressionist actions: [:item_detail]

  def list_country
    @countries = Country.all
  end

  def show_item_by_country
    @country = Country.find(params[:country_id])
    @ship_tos = @country.items
    @ship_froms = Item.where(ship_from: params[:country_id])
  end

  def dashboard
    @countries = Country.all.collect { |country| ["#{country.name}", country.id] }
    params[:country] = current_user.location.to_i    
    @items = Item.qty_available.get_filtered_items(params)
  end

  def dashboard_vendor
    dashboard
  end

  def show_buyer
    @user = current_user
    @bitcoin_address = @user.addresses.where(is_active: true).first.address.gsub(/\n/, '')
    @bitcoin_balance = @bitcoind_payment_method.status ? `bitcoin-cli getbalance #{current_user.username}` : @wallet.get_balance()

    check_pgp = File.exist? [Rails.root, "/public/pgp/users/#{@user.id}/publickey.asc"].join
    if check_pgp
      file = File.open("public/pgp/users/#{@user.id}/publickey.asc")
      publickey = file.read
      @publickey = publickey.gsub(/\r\n/, '<br/>')
    end
  end

  def item_detail
    bitcoin_balance = @bitcoind_payment_method.status ? `bitcoin-cli getbalance #{current_user.username}` : @wallet.get_balance()
    @item = Item.where(random_string: params[:random_string]).first

    item = Item.where(id: params[:id])
    category = @item.categories.first if @item

    @related_items = category.items - item if category.present?
    
    shippings = @item.user.shipping_options.collect { |shipping_option| ["#{shipping_option.name} (#{shipping_option.price} #{shipping_option.currency})", shipping_option.id] }
    data_collect = []
    data_first = []
    data_last = []

    shippings.each do |shipping|
      if shipping[0].downcase.include?("free")
        data_first << shipping
      else
        data_last << shipping
      end
      data_collect = data_first + data_last
    end
    @data = data_collect.uniq

    if current_user.role.eql?"Buyer"
      impressionist(@item)
    end

    @orders = @item.orders.where("feedback_comment IS NOT NULL").page(params[:page]).per(25)
  end

  def item_by_category
    @category = Category.find(params[:id])
    category_items = @category.items.joins(:countries, :user)
    @category_items = set_category_items(category_items)
  end

  def uncategories_items
    uncategories_items = Item.get_uncategories_items.joins(:countries, :user)
    @uncategories_items = set_category_items(uncategories_items)
  end

  def show_full_image
    @item = Item.where(random_string: params[:random_string]).first
    render layout: false
  end

  private

  def set_category_items(ci)
    country_id = current_user.location.to_i
    categories_items = 
      if country_id.zero?
        ci.where("users.last_active >= ? AND users.vacation_mode IS FALSE AND items.is_hidden IS FALSE AND items.quantity > 0 ", @seventy_two_hours_ago)
      else
        ci.where("users.last_active >= ? AND users.vacation_mode IS FALSE AND items.is_hidden IS FALSE AND items.quantity > 0 AND countries.id = ? ", @seventy_two_hours_ago, country_id)
      end

    categories_items
  end

  def seventy_two_hours_ago
    current_time = Time.now.utc
    @seventy_two_hours_ago = current_time - 72.hours
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/dashboard.html.slim
- if @blockchain_payment_method.status.eql?true
  .alert.alert-info role="alert"
    = "Welcome To #{@market_name.name rescue OpenFreeMarketTest}"
    br/
    | To make sure all bitcoin wallet function work. we need you to follow this step to enable api.
    ul#selector
      li = "Go to #{link_to "blockchain.info", "https://blockchain.info/wallet", :target => "_blank"}".html_safe
      li = "Login to your wallet and use #{current_user.identifier} for your indetifier to open your wallet"
      li = "Choose Account Settings."
      li = "Under IP Restrictions menu checklist 'Enable Api Access'"
    | If you still using our old wallet or your identifier still empty you can click create wallet menu

div style="margin-top: 60px;"
  / table
  - @items.each do |item|
    .well
      - if item.galleries.any?
        .col-md-3 style="margin-left: -25px;"
          .thumbnail
            = image_tag show_image(item.galleries.first.image.thumb.url), class: "lazy"
      - else
        .col-md-3 style="margin-left: -25px;"
          .thumbnail
            = image_tag image_path('no_image_w_large.gif')
      .col-md-7
        - if current_user.role.eql?("Vendor")
          = link_to "#{item.name}", item
        - else
          = link_to "#{item.name}", item_detail_url(item.random_string), :"data-no-turbolink" => "true"
        br/
        - if item.unlimited
          | this item is unlimited
        - else
          = "#{item.quantity} available"
        br/
        - if (item.currency.eql?"Bitcoin") || (item.currency.eql?"BCH")
            = item.price_with_precision
            | &nbsp; BCH
        - else
          = item.price_with_precision
          = " #{item.currency}"
          br/
          - if current_user.currency.present?
            - if (current_user.currency.eql?"Bitcoin") || (current_user.currency.eql?"BCH")
              - group = @rates.select { |element_hash| element_hash["code"].eql?"#{item.currency}" }
              - @price = item.price.to_f / group.first['rate'].to_f
              = convert_float_to_decimal(convert_float_to_decimal(@price).to_f.round(5))
              | &nbsp; BCH
            - else
              - if current_user.currency.eql? "United States Dollar"
                - current_user.currency = "USD"
              - elsif current_user.currency.eql? "Indonesian Rupiah"
                - current_user.currency = "IDR"
              - group = @rates.select { |element_hash| element_hash["code"].eql?"#{item.currency}" }
              - group_local = @rates.select { |element_hash| element_hash["code"].eql?"#{current_user.currency}" }
              - @price = item.price.to_f / group.first['rate'].to_f
              - @price_local = @price.to_f * group_local.first['rate'].to_f
              = convert_float_to_decimal(convert_float_to_decimal(@price).to_f.round(5))
              | &nbsp; BCH
        br/
        = "From : #{item.country.name if item.country}"
        br/
        | Vendor : #{ link_to(item.user.username, show_sender_detail_path(user_id: item.user.id)) }
      div style="clear: both;"

= paginate @items

app/views/dashboard/item_by_category.html.slim
h1 = @category.name

- @category_items.each do |item|
  .well
    - if item.galleries.any?
      .col-md-3 style="margin-left: -25px;"
        .thumbnail
          - item_image_url = item.galleries.first.image.thumb.url
          = image_tag show_image(item_image_url), class: "lazy"
    - else
      .col-md-3 style="margin-left: -25px;"
        .thumbnail
          = image_tag image_path('no_image_w_large.gif')
    .col-md-7
      - if current_user.role.eql?("Vendor")
        = link_to "#{item.name}", item
      - else
        = link_to "#{item.name}", item_detail_url(item.random_string), :"data-no-turbolink" => "true"
      br/
      - if item.unlimited
        | this item is unlimited
      - else
        = "#{item.quantity} available"
      br/
      - if (item.currency.eql?"Bitcoin") || (item.currency.eql?"BCH")
          = item.price_with_precision
          | &nbsp; BCH
      - else
        = item.price_with_precision
        = " #{item.currency}"
        br/
        - if current_user.currency.present?
          - if (current_user.currency.eql?"Bitcoin") || (current_user.currency.eql?"BHC")
            - group = @rates.select { |element_hash| element_hash["code"].eql?"#{item.currency}" }
            - @price = item.price.to_f / group.first['rate'].to_f
            = convert_float_to_decimal(convert_float_to_decimal(@price).to_f.round(5))
            | &nbsp; BCH
          - else
            - if current_user.currency.eql?"United States Dollar"
              - current_user.currency = "USD"
            - elsif current_user.currency.eql?"Indonesian Rupiah"
              - current_user.currency = "IDR"
            - group = @rates.select { |element_hash| element_hash["code"].eql?"#{item.currency}" }
            - group_local = @rates.select { |element_hash| element_hash["code"].eql?"#{current_user.currency}" }
            - @price = item.price.to_f / group.first['rate'].to_f
            - @price_local = @price.to_f * group_local.first['rate'].to_f
            = convert_float_to_decimal(convert_float_to_decimal(@price).to_f.round(5))
            | &nbsp; BCH
      br/
      = "From : #{item.country.name if item.country}"
      br/
      | Vendor : #{ link_to(item.user.username, show_sender_detail_path(user_id: item.user.id)) }
      / = "#{item.user.username} #{rating(item.user.id)}, #{order_size(item.user.id)}"
    div style="clear: both;"

app/views/dashboard/item_detail.html.slim
p#notice = notice

- if params[:quantity].present?
  .alert.alert-danger role="alert" id="alert-box"
    | Sorry the quantity of item cannot process your order.
- elsif params[:min].present?
  .alert.alert-danger role="alert" id="alert-box"
    | Sorry your quantity order must be equal 1 or higger than 1
- elsif params[:price].present?
  .alert.alert-danger role="alert" id="alert-box"
    | #{t('.alert1')}
- elsif params[:shopping_cart_id].present? && params[:diff].present?
  .alert.alert-danger role="alert" id="alert-box"
    | #{t('.alert2')}
  .alert.alert-warning role="alert" id="alert-box"
    | #{t('.alert3')} #{link_to "#{t('.here')}", shopping_cart_path(shopping_cart_id: params[:order_id]), :"data-no-turbolink" => "true"}
- elsif params[:shopping_cart_id].present?
  .alert.alert-warning role="alert" id="alert-box"
    | #{t('.alert3')} #{link_to "#{t('.here')}", shopping_cart_path(shopping_cart_id: params[:order_id]), :"data-no-turbolink" => "true"}

h2
  div style="float:left;"
    strong
      = "#{@item.name}"
    | &nbsp;
  div style="color: #428bca;"
    = link_to "#{@item.user.username}", show_sender_detail_path(user_id: @item.user.id)
p
  = "#{@item.categories.first.name rescue 'no categories'} -> #{@item.name}"

.panel.panel-default
  .panel-body
    = simple_form_for :add_order, url: shopping_cart_path, method: :post, :html => { :style => 'text-align: center;'}  do |f|
      .col-md-3 
        strong
          - if (@item.currency.eql?"Bitcoin") || (@item.currency.eql?"BCH")
            = "#{@item.price_with_precision.to_f.round(5)} #{@item.currency}"
          - else
            - if (current_user.currency.eql?"Bitcoin") || (current_user.currency.eql?"BCH")
              - group = @rates.select { |element_hash| element_hash["code"].eql?"#{@item.currency}" }
              - @price = @item.price.to_f / group.first['rate'].to_f
              | &nbsp; &nbsp; &nbsp;
              = "#{convert_float_to_decimal(convert_float_to_decimal(@price).to_f.round(5))} BCH"
            - else
              - if current_user.currency.eql?"United States Dollar"
                - current_user.currency = "USD"
              - elsif current_user.currency.eql?"Indonesian Rupiah"
                - current_user.currency = "IDR"
              - group = @rates.select { |element_hash| element_hash["code"].eql?"#{@item.currency}" }
              - group_local = @rates.select { |element_hash| element_hash["code"].eql?"#{current_user.currency}" }
              - @price = @item.price.to_f / group.first['rate'].to_f
              - @price_local = @price.to_f * group_local.first['rate'].to_f
              | &nbsp; &nbsp; &nbsp;
              = "#{convert_float_to_decimal(convert_float_to_decimal(@price).to_f.round(5))} BCH"
              br/
              | &nbsp; &nbsp; &nbsp;
              = "#{convert_float_to_decimal(convert_float_to_decimal(@price_local).to_f.round(5))} #{current_user.currency}"
          br/
      | &nbsp; #{t('.add')}
      = hidden_field_tag "item_id", @item.id
      = hidden_field_tag "shopping_cart_id", params[:shopping_cart_id]
      = text_field_tag "quantity", '1', type: :number, required: true
      - if @item.unlimited
        | this item is unlimited
      - else
        = "/ #{@item.quantity} #{t('.available')}, #{t('.ship')} "
      = select_tag "shipping", options_for_select(@data)
      | &nbsp;
      = f.submit "#{t('.add_order')}", class: "btn btn-success"

.col-md-3
  div style="text-align: right;"
    = "#{@item.price_with_precision} #{@item.currency} #{t('.each')}"
    br/
    = "#{t('.ship_from')} #{@item.country.name rescue nil}"
    br/
    - if @item.unlimited
      | this item is unlimited
    - else
      = "#{@item.quantity} #{t('.available')}"

.col-md-6
  .col-sm-12
    div
      - if @item.galleries.any?
        .thumbnail
          = image_tag show_image(@item.galleries.first.image.thumb.url), class: "lazy"
      - else
        .thumbnail style="height: 149px; width: 238px;"
          = image_tag image_path('no_image_w_large.gif')
      = link_to "#{t('.click')}", show_full_image_path(@item.random_string), target: "_blank"
      br
      = @item.description.html_safe
    br/
    br/
    div
      span
        b Feedbacks/Review
      ul
        - @orders.each do |order|
          - if order.feedback_comment.present?
            li = order.feedback_comment
      = paginate @orders
.col-md-3
  - if current_user.role.eql?"Buyer"
    = link_to "#{t('.message')} #{@item.user.username}", new_private_message_path(receiver_id: @item.user_id), class: "btn btn-default"
  - else
    = link_to "#{t('.message')} #{@item.user.username}", "javascript:void(0);", class: "btn btn-default"

div style="clear: both;"
br/

app/views/dashboard/show_full_image.html.slim
- if @item.galleries.any?
  - item_image_url = @item.galleries.first.image.url
  / - if item_image_url.include? "https"
  / - else
  /   - item_image_url["http"] = "https"
  = image_tag item_image_url, class: "lazy"
- else
  = image_tag image_path('no_image_w_large.gif')

app/views/dashboard/uncategories_items.html.slim
h1 Uncategory

- @uncategories_items.each do |item|
  .well
    - if item.galleries.any?
      .col-md-3 style="margin-left: -25px;"
        .thumbnail
          - item_image_url = item.galleries.first.image.thumb.url
          / - if item_image_url.include? "https"
          / - else
          /   - item_image_url["http"] = "https"
          = image_tag item_image_url, class: "lazy"
    - else
      .col-md-3 style="margin-left: -25px;"
        .thumbnail
          = image_tag image_path('no_image_w_large.gif')
    .col-md-7
      - if current_user.role.eql?("Vendor")
        = link_to "#{item.name}", item
      - else
        = link_to "#{item.name}", item_detail_url(item.random_string), :"data-no-turbolink" => "true"
      br/
      = "#{item.quantity} available"
      br/
      | BCH &nbsp;
      = item.price_with_precision
    div style="clear: both;"