config/routes.rb
Rails.application.routes.draw do

  apipie
  resources :addresses

  resources :messages

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  scope "(:locale)" do
    resources :private_messages
    get "support_contact" => "private_messages#support_contact"
    post "message_support_contact" => "private_messages#message_support_contact"
    get "reply" => "private_messages#reply"
    get "trash" => "private_messages#trash"
    get "untrash" => "private_messages#untrash"
    get "show_pgp" => "private_messages#show_pgp"
    get "show_sender_detail" => "private_messages#show_sender_detail"
    get "read_conversation" => "private_messages#read_conversation"
    get "unread_conversation" => "private_messages#unread_conversation"
    get "trash_private_message" => "private_messages#trash_private_message"
    get "untrash_private_message" => "private_messages#untrash_private_message"
    get "read_private_message" => "private_messages#read_private_message"
    get "unread_private_message" => "private_messages#unread_private_message"
    
    resources :orders do 
      post "confirm_order" => "orders#confirm_order"
      get "shipped_order" => "orders#shipped_order"
      post "request_buyer_attention_order" => "orders#request_buyer_attention_order"
      post "partially_shipped_order" => "orders#partially_shipped_order"
      get "cancel_order" => "orders#cancel"
    end
    
    get "auth_payment" => "orders#auth_payment" 
    post "finalize_order" => "orders#finalize_order"
    post "sent_order" => "orders#sent_order"
    get "orders/details/:id" => "orders#order_detail", as: :order_detail
    get "order_list" => "orders#order_list", as: :orders_list
    get "waiting_list" => "orders#waiting_list", as: :waiting_list
    get "approve_and_sent_orders" => "orders#approve_and_sent_orders", as: :approve_and_sent_orders
    post "pay" => "orders#pay", as: :pay
    get "pay_order_in_order" => "orders#pay_order_in_order", as: :pay_order_in_order
    get "pay_multisig" => "orders#pay_multisig"
    get "account_btc" => "orders#account", as: :bitcoin_account
    post "withdraw_funds" => "orders#withdraw_funds"
    post "transfer_fund" => "orders#transfer_fund"
    get "member" => "orders#member"
    get "create_new_bitcoin_address" => "orders#create_new_bitcoin_address", as: :create_new_bitcoin_address
    get "form_refund" => "orders#form_refund"
    post "refund_order" => "orders#refund_order", as: :refund_order
    get "validate_wallet" => "orders#validate_wallet", as: :validate_wallet
    get "pay_if_fund_not_enough" => "orders#pay_if_fund_not_enough", as: :pay_if_fund_not_enough

    resources :items, except: [:destroy]
    get "destroy_item" => "items#destroy"
    get "destroy_shipping_option" => "items#destroy_shipping_option"
    get "confirm_delete" => "items#confirm_delete", as: :confirm_delete
    get "copy_item" => "items#copy_item", as: :copy_item
    get "change_status" => "items#change_status", as: :change_status
    get "shipping_option/new" => "items#shipping_option_new"
    post "shipping_options" => "items#create_shpping_option_new"
    get "shipping_option_list" => "items#shipping_option_list", as: :shipping_option_list
    get "shipping_option/:id/edit" => "items#shipping_option_edit", as: :shipping_option_edit
    patch "shipping_option/:id" => "items#update_shipping_options", as: :shipping_option
    get "vendor_item" => "items#vendor_item"

    resources :categories
    resource :shopping_cart
    get "delete_cart/:id" => "shopping_carts#delete_cart", as: :delete_cart
    post "shopping_carts/encrypt_shipping_information"
    post "shopping_carts/pay_page"
    get "pay_order" => "shopping_carts#pay_order", as: :pay_order
    get "create_multi_sig" => "shopping_carts#create_multi_sig"
    post "shopping_carts/generate_multi_sig"
    get "pay_qr" => "shopping_cart#pay_qr", as: :pay_qr

    devise_scope :user do
      get 'users/vendor_sign_up', to: 'users/registrations#vendor_sign_up', as: 'vendor_sign_up'
      get ":token/register", to: "users/registrations#new"
    end
    devise_for :users, :controllers => { :registrations => "users/registrations", :sessions => "users/sessions" }
    resources :conversations, only: [:index, :show, :new, :create] do
      collection do
        get :inbox
        get :sentbox
        get :trash_list
      end
      member do
        post :reply
        post :trash
        post :untrash
      end
    end
    get "uncategories_items" => "dashboard#uncategories_items", as: :uncategories_items
    get "item_search" => "dashboard#item_search", as: :item_search
    get "category/:id" => "dashboard#item_by_category", as: :item_by_category
    get "dashboard" => "dashboard#dashboard", as: :dashboard
    post "dashboard" => "dashboard#dashboard", as: :dashboard_post
    get "dashboard_vendor" => "dashboard#dashboard_vendor", as: :dashboard_vendor
    post "dashboard_vendor" => "dashboard#dashboard_vendor", as: :dashboard_vendor_post
    get "list_country" => "dashboard#list_country"
    get "show_item_by_country" => "dashboard#show_item_by_country"
    get "item-detail/:random_string" => "dashboard#item_detail", as: :item_detail
    get "account" => "dashboard#show_buyer", as: :buyer_account
    get "show_full_image/:random_string" => "dashboard#show_full_image", as: :show_full_image
    get "upload-pgp-key" => "pgp#upload_key"
    post "pgp/check_pgp_key"
    get "input_string" => "pgp#input_string"
    get "input_string_from_profile" => "pgp#input_string_from_profile" 
    get "input_string_first_time" => "pgp#input_string_first_time" 
    get "confirmation_change_password" => "pgp#confirmation_change_password"
    get "change_password" => "pgp#change_password"
    post "pgp/check_random_string"
    post "pgp/check_random_string_from_profile"
    post "pgp/check_random_string_first_time"
    post "pgp/confirm_new_password"
    get "history" => "history#index", as: :history
    get "home" => "home#index"
    get "invite_new_buyer" => "invites#invite_new_buyer"
    get "invites/cancel_invited"
    post "invites/sent_invitation"
    get "new_wallet" => "blockchain#new_wallet"
    post "blockchain/create_new_wallet"
    # get '*path' => redirect("/")

    root 'home#index'
  end

  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'login' => 'sessions#create', as: 'login'
        delete 'logout' => 'sessions#destroy', as: 'logout'
      end
      get "dashboard" => "dashboard#dashboard"
      get "dashboard_vendor" => "dashboard#dashboard_vendor"
      get "category/:id" => "dashboard#item_by_category", as: :item_by_category
      get "account" => "dashboard#show_buyer", as: :buyer_account
      get "item-detail/:id" => "dashboard#item_detail"

      get "categories" => "categories#index"

      get "shipping_options" => "shipping_options#index"
      get "shipping_options/:id/edit" => "shipping_options#edit"
      post "shipping_options/:id" => "shipping_options#update"
      post "create_shipping_option" => "shipping_options#create"

      get "countries" => "countries#index"
      get "ship_from" => "countries#ship_from"
      get "ship_to" => "countries#ship_to"

      get "currencies" => "currency_config#index"

      post "create_user" => "users#create"
      get "users/:id/edit" => "users#edit"
      post "users/:id" => "users#update"

      get "messages" => "messages#index"
      get "list_recipient" => "messages#list_recipient"
      get "create_message" => "messages#create_message"
      post "sent_message" => "messages#sent_message"
      get "reply" => "messages#reply"
      get "support_contact" => "messages#support_contact"
      post "message_support_contact" => "messages#message_support_contact"

      get "items" => "items#index"
      get "copy_item" => "items#copy_item"
      get "change_status" => "items#change_status"
      get "destroy_item" => "items#destroy"
      get "items/:id/edit" => "items#edit"
      post "items/:id" => "items#update"
      post "create_item" => "items#create"

      get "order_list" => "orders#order_list"
      get "orders" => "orders#index"
      get "orders/:order_id/shipped_order" => "orders#shipped_order"
      post "sent_order" => "orders#sent_order"
      get "form_refund" => "orders#form_refund"
      post "refund_order" => "orders#refund_order"
      post "finalize_order" => "orders#finalize_order"
      get "account_btc" => "orders#account"
      get "create_new_bitcoin_address" => "orders#create_new_bitcoin_address"
      get "member" => "orders#member"
      post "withdraw_funds" => "orders#withdraw_funds"
      post "transfer_fund" => "orders#transfer_fund"
      get "pay_order_in_order" => "orders#pay_order_in_order"

      post "shopping_cart" => "shopping_carts#create"
      post "shopping_carts/update_order"
      get "shopping_cart" => "shopping_carts#show"
      post "shopping_carts/message_information"
      get "pay" => "shopping_carts#pay"
      post '/delete_cart/:id' => "shopping_carts#delete_cart"
    end  
  end
end

app/controllers/api/v1/shopping_carts_controller.rb
class Api::V1::ShoppingCartsController < ApiController
  skip_before_filter :verify_authenticity_token
  before_filter :extract_shopping_cart

  api :POST, '/v1/shopping_cart', 'Create a order'
  param :auth_token, String, desc: "Authentication Token User", required: true
  param :shopping_cart_id, String, desc: "Id of shopping cart"
  param :item_id, String, desc: "Id of item"
  param :quantity, String, desc: "Quantity item will be order"
  param :shipping, String, desc: "Shipping of order"
  def create
    current_user = User.where(authentication_token: params[:auth_token]).first
    bitcoin_balance = `bitcoin-cli getbalance #{current_user.username}`
    @item = Item.find(params[:item_id])
    if params[:quantity].to_i < 1
      render json: { status: "Sorry your quantity order must be equal 1 or higger than 1" }, status: :unprocessable_entity
    else
      new_quantity = @item.quantity - params[:quantity].to_i
      price = @item.price * params[:quantity].to_i
      shipping = ShippingOption.find(params[:shipping]).price
      total = price + shipping
      if params[:quantity].to_i > @item.quantity
        render json: { status: "Sorry the quantity of item cannot process your order." }, status: :unprocessable_entity
      # elsif total >= bitcoin_balance.to_f
      #   render json: { status: "Sorry you bitcoin balance is not enough for buy this item." }, status: :unprocessable_entity
      elsif params[:shopping_cart_id].present?
        shopping_cart = ShoppingCart.find(params[:shopping_cart_id])
        vendor_item = shopping_cart.shopping_cart_items.first
        if @item.user.username === vendor_item.item.user.username
          @shopping_cart.add(@item, @item.price)
          cart_item = @shopping_cart.shopping_cart_items.last
          cart_item.shipping_id = params[:shipping]
          cart_item.save
          @item.quantity = new_quantity
          @item.save
          @order = Order.create({user_id: current_user.id, item_id: params[:item_id], quantity: params[:quantity], total_payment: total, status: "Not Pay", shipping_id: params[:shipping]})
          render json: { status: "Order successfully create" }, status: :created
        elsif @item.user.name != vendor_item.item.user.username
          render json: { status: "Sorry for now we cann't handle for multiple vendor. Please select item with same vendor with you first item in your cart." }, status: :unprocessable_entity
        end
      else
        @shopping_cart.add(@item, @item.price)
        cart_item = @shopping_cart.shopping_cart_items.last
        cart_item.shipping_id = params[:shipping]
        cart_item.save
        @item.quantity = new_quantity
        @item.save
        @order = Order.create({user_id: current_user.id, item_id: params[:item_id], quantity: params[:quantity], total_payment: total, status: "Not Pay", shipping_id: params[:shipping]})
        render json: { status: "Order successfully create", shopping_cart_id: @shopping_cart.id }, status: :created
      end
    end
  end

  api :GET, '/v1/shopping_cart', 'Show shopping cart item'
  param :shopping_cart_id, String, desc: "Id of shopping cart"
  def show
    @bitcoin_balance = `bitcoin-cli getbalance #{current_user.username}`
    render 'api/v1/shopping_carts/show'
  end

  api :POST, '/v1/shopping_carts/update_order', 'Create a order'
  param :shopping_cart_id, String, desc: "Id of shopping cart"
  param :shopping_cart_item_id, Hash, desc: "Id of shopping cart item, params must be like shopping_cart_id [n], n start from 1"
  param :price, Hash, desc: "Price of item, params must be like price [n], n start from 1"
  param :quantity, Hash, desc: "Quantity item will be order, params must be like quantity [n], n start from 1"
  param :shipping, Hash, desc: "Shipping of order, params must be like shipping [n], n start from 1"
  def update_order
    id = params[:shopping_cart_item_id]
    price = params[:price]
    shipping = params[:shipping]
    quantity = params[:quantity]

    #merge params
    temp = id.merge(price){|key,oldval,newval| [*oldval].to_a + [*newval].to_a}
    temp1 = temp.merge(shipping){|key,oldval,newval| [*oldval].to_a + [*newval].to_a}
    hash = temp1.merge(quantity){|key,oldval,newval| [*oldval].to_a + [*newval].to_a}

    hash.each do |key, value|
      @shopping_cart_item = ShoppingCartItem.find(value[0])
      puts value[1]
      puts value[1].eql?(0)
      puts value[1].blank?
      unless value[1].to_i.zero? || value[1].blank?
        @shopping_cart_item.price = value[1]
      end
      @shopping_cart_item.quantity = value[3]
      @shopping_cart_item.shipping_id = value[2]
      @shopping_cart_item.save
    end
    render json: { status: "Your cart already updated" }, status: :created
  end

  api :POST, '/v1/shopping_carts/message_information', 'Create a message information'
  param :auth_token, String, desc: "Authentication Token User", required: true
  param :shopping_cart_id, String, desc: "Id of shopping cart"
  param :message, String, desc: "Addtional Message"
  def message_information
    current_user = User.where(authentication_token: params[:auth_token]).first
    # item = Item.find(params[:item_id])
    # file_buyer = File.exists? ("public/pgp/users/#{current_user.id}/key.txt")
    # file_vendor = File.exists? ("public/pgp/users/#{item.user.id}/key.txt")
    
    # if file_buyer.present?
    #   email = nil
    #   key = `gpg --import "public/pgp/users/#{current_user.id}/publickey.asc" 2>&1`
    # else
    #   email = nil
    #   key = `gpg --import "public/pgp/users/#{item.user.id}/publickey.asc" 2>&1`
    # end
    # key.scan(/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b/i) { |x| email = x }
    # crypto = GPGME::Crypto.new(:armor => true, :always_trust => true)
    
    # if email.present?
    #   params[:message] = crypto.encrypt "#{params[:message]}", :recipients => "#{email}"
    # else
    #   params[:message] = crypto.encrypt "#{params[:message]}"
    # end  
    # params[:message] = params[:message].read
    additional_informartion_message = AdditionalInformartionMessage.create({ message: params[:message] })

    shopping_cart = ShoppingCart.find(params[:shopping_cart_id])
    shopping_cart.additional_information_message_id = additional_informartion_message.id
    shopping_cart.save
    render json: { status: "Your additional information already created" }, status: :created
  end

  api :GET, '/v1/pay', 'Pay order'
  param :auth_token, String, desc: "Authentication Token User", required: true
  param :shopping_cart, String, desc: "id of shopping cart"
  def pay
    current_user = User.where(authentication_token: params[:auth_token]).first
    shopping_cart = ShoppingCart.pay(params, current_user)

    render json: { status: "Congratulations your order is paid. Vendor must now confirm your order." }, status: :created
  end

  api :POST, '/v1/delete_cart/:id', "Delete order in cart"
  param :shopping_cart, String, desc: "id of shopping cart"
  param :id, String, desc: "id of shopping cart item"
  def delete_cart
    shopping_cart_item = ShoppingCartItem.find(params[:id])
    @item = Item.find(shopping_cart_item.item_id)
    @shopping_cart.remove(@item, shopping_cart_item.quantity)
    render json: { status: "Your order has been deleted" }, status: :deleted
  end

  private
  def extract_shopping_cart
    shopping_cart_id = params[:shopping_cart_id]
    @shopping_cart = params[:shopping_cart_id] ? ShoppingCart.find(shopping_cart_id) : ShoppingCart.create
    session[:shopping_cart_id] = @shopping_cart.id
  end
end

app/views/shopping_carts/_shopping_cart_item.html.slim
tr.order-list style="background: #D2E0ED;"
  td
    - index = shopping_cart_item_counter + 1
    = link_to "#{shopping_cart_item.item.name rescue nil}", item_detail_url(shopping_cart_item.item.random_string), :"data-no-turbolink" => "true"
    = hidden_field_tag "shopping_cart_item_id[#{index}]", shopping_cart_item.id rescue nil
    = text_field_tag "price[#{index}]", shopping_cart_item.item.price, class: "price", style: "display: none;"
  td
    = link_to "#{shopping_cart_item.item.user.username rescue nil}", show_sender_detail_path(user_id: shopping_cart_item.item.user.id) 
  td
    - shippings = shopping_cart_item.item.user.shipping_options.collect{ |shipping_option| ["#{shipping_option.name} (#{convert_to_btc(shipping_option.currency, shipping_option.price)} BCH)", shipping_option.id]}
    - shippings_price = shopping_cart_item.item.user.shipping_options.collect{ |shipping_option| [shipping_option.name, shipping_option.price]}
    
    - if shopping_cart_item.shipping_id.present?
      = select_tag "shipping[#{index}]", options_for_select(shippings, shopping_cart_item.shipping_id), class: "shipping"
    - else
      = select_tag "shipping[#{index}]", options_for_select(shippings), class: "shipping"
  td
    = text_field_tag "quantity[#{index}]", shopping_cart_item.quantity, type: :number, required: true, class: "quantity"
    - if params[:message].present?
      = "#{shopping_cart_item.quantity} #{shopping_cart_item.item.name rescue nil}, only #{get_item(shopping_cart_item.item_id)} available"
  td
    = "#{convert_float_to_decimal(shopping_cart_item.price.to_f.round(5))} BCH"
  td
    = link_to "#{t('.delete')}", delete_cart_url(id: shopping_cart_item.id ), data: {:confirm => 'Are you sure?'}, :method => :get, class: "btn btn-danger"

app/views/shopping_carts/create_multi_sig.html.slim
- if params["multi_sig"].present?
  .panel.panel-info
    .panel-heading
      | The Address of multisig
    .panel-body
      | Address
      = text_field_tag "address", "#{params["multi_sig"]['address']}", class: "form-control", readonly: true
      br/
      | Redeem Script
      = text_area_tag "redeem_script", "#{params["multi_sig"]['redeemScript']}", class: "form-control", style: "height: 130px;", readonly: true
      h5
        | Note:
        br/
        | Please keep the address and redeem script somewhere in your computer.
  = link_to "Send payment of #{convert_float_to_decimal(calculate_total(@shopping_cart))} BCH", pay_multisig_path(shopping_cart: @shopping_cart.id, multisig_address: params["multi_sig"]['address']), class: "btn btn-success"
- else
  h3
   | New Multisig Address Secure multisig address.

  h5
    | Just input vendor address and your address we will generate your public key, address for transfer the bch using multisig also the redeem script.

  = simple_form_for :generate_multi_sig, url: shopping_carts_generate_multi_sig_path, method: :post do |f|
    = text_field_tag "vendor_pub_key", @vendor_address, class: "form-control", placeholder: "Vendor Address", readonly: true
    br/
    = text_field_tag "buyer_pub_key", @buyer_address, class: "form-control", placeholder: "Buyer Address", readonly: true
    br/
    = text_field_tag "escrow_pub_key", @escrow_address, class: "form-control", placeholder: "Escrow Address", readonly: true, style: "display: none;"
    = text_field_tag "shopping_cart", params[:shopping_cart], style: "display: none;"
    br/
    = f.submit "Submit", class: "btn btn-primary"

app/views/shopping_carts/pay_order.html.slim
- unless @bitcoin_balance.present?
  #notice
    .alert.alert-success 
      = "bitcoin not configured properly on server. bitcoin functions currently unavailable."

- subtotal = @shopping_cart.shopping_cart_items.map{ |item| item.quantity*item.price}.sum

table.table.table-bordered style="margin-top: 40px;"
  tr
    th Product
    th Vendor
    th Shipping
    th 
      div style="text-align:center;"
        | Quantity
    th 
      div style="text-align:right;"
        | Subtotal USD 
        br/ 
        | (Inc Ship)
  - @shopping_cart.shopping_cart_items.each do |shopping_cart_item|
    tr
      td
        = shopping_cart_item.item.name 
      td
        = shopping_cart_item.item.user.username
      td
        = shopping_cart_item.shipping_option.name
      td
        div style="text-align:center;"
          = shopping_cart_item.quantity
      td
        div style="text-align:right;"
          = convert_float_to_decimal(shopping_cart_item.price.round(6))
  tr
    td colspan="3"
    td
      div style="text-align:right; font-weight: bold;" Total Amount
    td
      div style="text-align:right;"
        = convert_float_to_decimal(calculate_total(@shopping_cart))
  tr
    td colspan="3"
    td
      div style="text-align:right; font-weight: bold;" Total BCH
    td
      div style="text-align:right;"
        = convert_float_to_decimal(calculate_total(@shopping_cart).to_f.round(6))

h4 Select a payment method:
- if @qr_status.eql?true
  .panel.panel-default
    .panel-heading
      .panel-title style="height: 20px;"
        div style="float: left;"
          | Option 1. Pay using QR code
    .panel-body
      table.qrcode
        - @qr = RQRCode::QRCode.new( "bitcoin:#{ @escrow_address.gsub(/\n/, '') }?amount=#{convert_float_to_decimal(calculate_total(@shopping_cart))}\&label=Example\&message=#{@shopping_cart.id}\&r=#{request.protocol + request.host}/pay_qr/#{@shopping_cart.id}", :size => 11, :level => :h )
        - @qr.modules.each_index do |x|
          tr
          - @qr.modules.each_index do |y|
            - if @qr.dark?(x,y) 
              td.black
            - else 
              td.white
      br/
      | Bitcoin Address : #{ @escrow_address }
      br/
      | Total payment : #{ convert_float_to_decimal(calculate_total(@shopping_cart)) } BCH
.panel.panel-default
  .panel-heading
    .panel-title style="height: 20px;"
      div style="float: left;"
        - if @qr_status.eql?true
          | Option 2. Pay using your #{@market_name.name } wallet - You have #{@bitcoin_balance.to_f.round(5)} BCH available
        - else
          | Pay using your #{@market_name.name } wallet - You have #{@bitcoin_balance.to_f.round(5)} BCH available
  .panel-body
    = form_tag("/orders/pay", method: "post" ) do
      
      .col-md-2 style="text-align: right;"
        | Password:
      .col-md-10
        = password_field_tag "password", '', style: "width: 250px;", required: true, class: 'password optional form-control'
        = text_field_tag "shopping_cart", @shopping_cart.id, style: "display: none;", required: true, class: 'password optional form-control'
      div style="clear: both;"
      br/
      .col-md-2
      .col-md-10
        = submit_tag "Send BCH", class: "btn btn-default btn-success"
    / = link_to "Send payment of #{convert_float_to_decimal(calculate_total(@shopping_cart))} BTC", validate_wallet_path(shopping_cart: @shopping_cart.id, order_id: params[:order_id]), class: "btn btn-success"
- if @multisig.present?
  - if @multisig.status.eql?true
    .panel.panel-default
      .panel-heading
        .panel-title Option 3. Pay using Bitcoin Multi-sig escrow
      .panel-body
        div style="font-size: 12px;"
          = link_to "Pay Using Multisig", create_multi_sig_path(shopping_cart: @shopping_cart.id, vendor_name: @shopping_cart.shopping_cart_items.first.item.user.username), class: "btn btn-primary"

app/views/shopping_carts/show.html.slim
- if params[:back].present?
  .alert.alert-danger role="alert" id="alert-box"
    | Please upload a pgp key to encrypt this message because vendor for now not upload pgp key
- elsif params[:success].present?
  .alert.alert-warning role="alert" id="alert-box"
    | Your cart already updated
h5
  = "You have #{convert_float_to_decimal(@bitcoin_balance.to_f.round(6))} BCH available (#{@local_currency.to_f.round(6)} #{current_user.currency})"

h4 
  | Cart

= form_tag("/shopping_carts/encrypt_shipping_information", method: "post" ) do
  table.table.table-bordered
    tr
      td #{t('.product')}
      td #{t('.vendor')}
      td #{t('.shipping')}
      td #{t('.quantity')}
      td 
        | #{t('.sub')} 
        br/ 
        | #{t('.inc')}
      td

    = render :partial => 'shopping_cart_item', :collection => @shopping_cart.shopping_cart_items
    tr
      td colspan="3"
      td Total Amount
      td = "#{convert_float_to_decimal(calculate_total(@shopping_cart).to_f.round(6))} BCH"
    tr
      td colspan="3"
      td Total BCH
      td
        = "#{convert_float_to_decimal(calculate_total(@shopping_cart).to_f.round(6))} BCH"
      td
    tr
      td colspan="3"
      td Total #{current_user.currency}
      td
        - group = @rates.select { |element_hash| element_hash["code"].eql?"#{current_user.currency}" }
        - @price = calculate_total(@shopping_cart).to_f * group.first['rate'].to_f
        | &nbsp; &nbsp; &nbsp; #{current_user.currency}
        | &nbsp;
        / = s
        = convert_float_to_decimal(convert_float_to_decimal(@price).to_f.round(6))
    = hidden_field_tag "item_id", @shopping_cart.shopping_cart_items.first.item_id rescue nil
  div style="text-align: right;"
    = submit_tag "#{t('.update')}", class: "btn btn-success"
  br/


= form_tag("/shopping_carts/pay_page", method: "post" ) do
  .panel.panel-default
    .panel-heading
      .panel-title #{t('.shipping')}
    .panel-body
      div style="font-size: 12px;"
      br/
      - if @shopping_cart.additional_informartion_message.present?
        = text_area_tag "message", @shopping_cart.additional_informartion_message.message, style: "width: 100%; height: 150px;"
      - elsif params[:message].present?
        = text_area_tag "message", params[:message], style: "width: 100%; height: 150px;"
      - else
        = text_area_tag "message", "", style: "width: 100%; height: 150px;"
      = hidden_field_tag "item_id", @shopping_cart.shopping_cart_items.first.item_id rescue nil
      = hidden_field_tag "shopping_cart_id", @shopping_cart.id
      = hidden_field_tag "order_id", params[:shopping_cart_id]
  .col-md-4
  .col-md-8
    div style="text-align: right;"
      = hidden_field_tag "shopping_cart_id", @shopping_cart.id
      = submit_tag "Create New Order", class: "btn btn-success"
      br/
      | Current price: 
      b
        - subtotal = @shopping_cart.shopping_cart_items.map{ |item| item.quantity*item.price}.sum
        = "#{convert_float_to_decimal(calculate_total(@shopping_cart).round(6))} BCH"