config/routes.rb
Rails.application.routes.draw do

  apipie
  resources :addresses

  resources :messages

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  scope "(:locale)" do
    resources :private_messages
    get "support_contact" => "private_messages#support_contact"
    post "message_support_contact" => "private_messages#message_support_contact"
    get "reply" => "private_messages#reply"
    get "trash" => "private_messages#trash"
    get "untrash" => "private_messages#untrash"
    get "show_pgp" => "private_messages#show_pgp"
    get "show_sender_detail" => "private_messages#show_sender_detail"
    get "read_conversation" => "private_messages#read_conversation"
    get "unread_conversation" => "private_messages#unread_conversation"
    get "trash_private_message" => "private_messages#trash_private_message"
    get "untrash_private_message" => "private_messages#untrash_private_message"
    get "read_private_message" => "private_messages#read_private_message"
    get "unread_private_message" => "private_messages#unread_private_message"
    
    resources :orders do 
      post "confirm_order" => "orders#confirm_order"
      get "shipped_order" => "orders#shipped_order"
      post "request_buyer_attention_order" => "orders#request_buyer_attention_order"
      post "partially_shipped_order" => "orders#partially_shipped_order"
      get "cancel_order" => "orders#cancel"
    end
    
    get "auth_payment" => "orders#auth_payment" 
    post "finalize_order" => "orders#finalize_order"
    post "sent_order" => "orders#sent_order"
    get "orders/details/:id" => "orders#order_detail", as: :order_detail
    get "order_list" => "orders#order_list", as: :orders_list
    get "waiting_list" => "orders#waiting_list", as: :waiting_list
    get "approve_and_sent_orders" => "orders#approve_and_sent_orders", as: :approve_and_sent_orders
    post "pay" => "orders#pay", as: :pay
    get "pay_order_in_order" => "orders#pay_order_in_order", as: :pay_order_in_order
    get "pay_multisig" => "orders#pay_multisig"
    get "account_btc" => "orders#account", as: :bitcoin_account
    post "withdraw_funds" => "orders#withdraw_funds"
    post "transfer_fund" => "orders#transfer_fund"
    get "member" => "orders#member"
    get "create_new_bitcoin_address" => "orders#create_new_bitcoin_address", as: :create_new_bitcoin_address
    get "form_refund" => "orders#form_refund"
    post "refund_order" => "orders#refund_order", as: :refund_order
    get "validate_wallet" => "orders#validate_wallet", as: :validate_wallet
    get "pay_if_fund_not_enough" => "orders#pay_if_fund_not_enough", as: :pay_if_fund_not_enough

    resources :items, except: [:destroy]
    get "destroy_item" => "items#destroy"
    get "destroy_shipping_option" => "items#destroy_shipping_option"
    get "confirm_delete" => "items#confirm_delete", as: :confirm_delete
    get "copy_item" => "items#copy_item", as: :copy_item
    get "change_status" => "items#change_status", as: :change_status
    get "shipping_option/new" => "items#shipping_option_new"
    post "shipping_options" => "items#create_shpping_option_new"
    get "shipping_option_list" => "items#shipping_option_list", as: :shipping_option_list
    get "shipping_option/:id/edit" => "items#shipping_option_edit", as: :shipping_option_edit
    patch "shipping_option/:id" => "items#update_shipping_options", as: :shipping_option
    get "vendor_item" => "items#vendor_item"

    resources :categories
    resource :shopping_cart
    get "delete_cart/:id" => "shopping_carts#delete_cart", as: :delete_cart
    post "shopping_carts/encrypt_shipping_information"
    post "shopping_carts/pay_page"
    get "pay_order" => "shopping_carts#pay_order", as: :pay_order
    get "create_multi_sig" => "shopping_carts#create_multi_sig"
    post "shopping_carts/generate_multi_sig"
    get "pay_qr" => "shopping_cart#pay_qr", as: :pay_qr

    devise_scope :user do
      get 'users/vendor_sign_up', to: 'users/registrations#vendor_sign_up', as: 'vendor_sign_up'
      get ":token/register", to: "users/registrations#new"
    end
    devise_for :users, :controllers => { :registrations => "users/registrations", :sessions => "users/sessions" }
    resources :conversations, only: [:index, :show, :new, :create] do
      collection do
        get :inbox
        get :sentbox
        get :trash_list
      end
      member do
        post :reply
        post :trash
        post :untrash
      end
    end
    get "uncategories_items" => "dashboard#uncategories_items", as: :uncategories_items
    get "item_search" => "dashboard#item_search", as: :item_search
    get "category/:id" => "dashboard#item_by_category", as: :item_by_category
    get "dashboard" => "dashboard#dashboard", as: :dashboard
    post "dashboard" => "dashboard#dashboard", as: :dashboard_post
    get "dashboard_vendor" => "dashboard#dashboard_vendor", as: :dashboard_vendor
    post "dashboard_vendor" => "dashboard#dashboard_vendor", as: :dashboard_vendor_post
    get "list_country" => "dashboard#list_country"
    get "show_item_by_country" => "dashboard#show_item_by_country"
    get "item-detail/:random_string" => "dashboard#item_detail", as: :item_detail
    get "account" => "dashboard#show_buyer", as: :buyer_account
    get "show_full_image/:random_string" => "dashboard#show_full_image", as: :show_full_image
    get "upload-pgp-key" => "pgp#upload_key"
    post "pgp/check_pgp_key"
    get "input_string" => "pgp#input_string"
    get "input_string_from_profile" => "pgp#input_string_from_profile" 
    get "input_string_first_time" => "pgp#input_string_first_time" 
    get "confirmation_change_password" => "pgp#confirmation_change_password"
    get "change_password" => "pgp#change_password"
    post "pgp/check_random_string"
    post "pgp/check_random_string_from_profile"
    post "pgp/check_random_string_first_time"
    post "pgp/confirm_new_password"
    get "history" => "history#index", as: :history
    get "home" => "home#index"
    get "invite_new_buyer" => "invites#invite_new_buyer"
    get "invites/cancel_invited"
    post "invites/sent_invitation"
    get "new_wallet" => "blockchain#new_wallet"
    post "blockchain/create_new_wallet"
    # get '*path' => redirect("/")

    root 'home#index'
  end

  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'login' => 'sessions#create', as: 'login'
        delete 'logout' => 'sessions#destroy', as: 'logout'
      end
      get "dashboard" => "dashboard#dashboard"
      get "dashboard_vendor" => "dashboard#dashboard_vendor"
      get "category/:id" => "dashboard#item_by_category", as: :item_by_category
      get "account" => "dashboard#show_buyer", as: :buyer_account
      get "item-detail/:id" => "dashboard#item_detail"

      get "categories" => "categories#index"

      get "shipping_options" => "shipping_options#index"
      get "shipping_options/:id/edit" => "shipping_options#edit"
      post "shipping_options/:id" => "shipping_options#update"
      post "create_shipping_option" => "shipping_options#create"

      get "countries" => "countries#index"
      get "ship_from" => "countries#ship_from"
      get "ship_to" => "countries#ship_to"

      get "currencies" => "currency_config#index"

      post "create_user" => "users#create"
      get "users/:id/edit" => "users#edit"
      post "users/:id" => "users#update"

      get "messages" => "messages#index"
      get "list_recipient" => "messages#list_recipient"
      get "create_message" => "messages#create_message"
      post "sent_message" => "messages#sent_message"
      get "reply" => "messages#reply"
      get "support_contact" => "messages#support_contact"
      post "message_support_contact" => "messages#message_support_contact"

      get "items" => "items#index"
      get "copy_item" => "items#copy_item"
      get "change_status" => "items#change_status"
      get "destroy_item" => "items#destroy"
      get "items/:id/edit" => "items#edit"
      post "items/:id" => "items#update"
      post "create_item" => "items#create"

      get "order_list" => "orders#order_list"
      get "orders" => "orders#index"
      get "orders/:order_id/shipped_order" => "orders#shipped_order"
      post "sent_order" => "orders#sent_order"
      get "form_refund" => "orders#form_refund"
      post "refund_order" => "orders#refund_order"
      post "finalize_order" => "orders#finalize_order"
      get "account_btc" => "orders#account"
      get "create_new_bitcoin_address" => "orders#create_new_bitcoin_address"
      get "member" => "orders#member"
      post "withdraw_funds" => "orders#withdraw_funds"
      post "transfer_fund" => "orders#transfer_fund"
      get "pay_order_in_order" => "orders#pay_order_in_order"

      post "shopping_cart" => "shopping_carts#create"
      post "shopping_carts/update_order"
      get "shopping_cart" => "shopping_carts#show"
      post "shopping_carts/message_information"
      get "pay" => "shopping_carts#pay"
      post '/delete_cart/:id' => "shopping_carts#delete_cart"
    end  
  end
end

app/controllers/private_messages_controller.rb
class PrivateMessagesController < InheritedResources::Base
  skip_before_action :market_name, only: [:reply]
  before_filter :authenticate_user!
  before_action :category
  before_action :fetch_conversation_user, only: [:read_conversation, :unread_conversation, :trash]
  before_action :fetch_private_message, only: [:trash_private_message, :untrash_private_message, :unread_private_message, :read_private_message]

  def show_sender_detail
    @sender = User.find(params[:user_id])
    check_pgp = File.exist? [Rails.root, "/public/pgp/users/#{@sender.id}/publickey.asc"].join
    if check_pgp.eql? true
      file = File.open("public/pgp/users/#{@sender.id}/publickey.asc")
      publickey = file.read
      @publickey = publickey.gsub(/\r\n/, '<br/>')
    end
  end

  def support_contact
    @support = User.where(role: "Support").first
    @private_message = PrivateMessage.new
  end

  def message_support_contact
    user = User.message_support_contact(current_user, params)
    
    redirect_to private_messages_path, notice: "Your message has been sent"
  end

  def index
    @private_message = PrivateMessage.new
    @conversations = current_user.receiver_conversations.order("updated_at DESC")
    if @conversations.empty?
      @conversations = current_user.conversations.order("updated_at DESC")
    end
  end

  def reply
    @user = User.where(username: params[:user]).first
    conversation_user = ConversationsUser.where("sender_id = ? AND receiver_id = ?", @user.id, current_user.id ).first
    conversation_user_1 = ConversationsUser.where("sender_id = ? AND receiver_id = ?", current_user.id, @user.id ).first
    if conversation_user.present?
      conversation_user.update_attributes(is_read: true)
      @private_message = PrivateMessage.new
      @recipient_id = @user.id
      @messages = conversation_user.conversation.private_messages.where(is_deleted: false).order("created_at DESC")
    elsif conversation_user_1.present?
      conversation_user.update_attributes(is_read: true)
      @private_message = PrivateMessage.new
      @recipient_id = @user.id
      @messages = conversation_user_1.conversation.private_messages.where(is_deleted: false).order("created_at DESC")
    else
      redirect_to private_messages_path, notice: "Sorry you can open that url"
    end
    
    market_name
  end

  def trash
    @conversation_user.destroy
    redirect_to private_messages_path
  end

  def read_conversation
    @conversation_user.update_attributes(is_read: true)    
    redirect_to private_messages_path
  end

  def unread_conversation
    @conversation_user.update_attributes(is_read: false)    
    redirect_to private_messages_path
  end

  def trash_private_message
    @private_message.destroy
    redirect_to private_messages_path
  end

  def untrash_private_message
    @private_message.update_attributes(is_deleted: false)
    redirect_to private_messages_path
  end

  def read_private_message
    @private_message.update_attributes(is_read: true)
    redirect_to private_messages_path
  end

  def unread_private_message
    @private_message.update_attributes(is_read: false)
    redirect_to private_messages_path
  end

  def untrash
    messages = PrivateMessage.where("(sender_id = :sender_id AND receiver_id = :receiver_id) OR (sender_id = :receiver_id AND receiver_id = :sender_id)", { sender_id: params[:sender_id], receiver_id: current_user.id})
    messages.update_all(status: "Sent")
    if inbox.present?
      if inbox.include? current_user.id
        @senders = User.find([inbox])
      end
    end
    redirect_to private_messages_path
  end

  def new
    @recieved = User.find(params[:receiver_id])
    @file = File.exists? ("public/pgp/users/#{@recieved.id}/key.txt")
    @private_message = PrivateMessage.new
  end

  def show_pgp
    @private_message = PrivateMessage.new
    @recieved = User.find(params[:id])
    if @recieved.present?
      email = nil
      key = `gpg --import "public/pgp/users/#{@recieved.id}/publickey.asc" 2>&1`
      @key = key.scan(/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b/i) { |x| email = x }
    end
  end

  def create
    if params[:private_message][:body].present?
      params[:private_message][:body] = params[:private_message][:body].gsub(/\n/, '<br/>')
      
      if params[:private_message][:receiver_id].present?
        receiver_id = params[:private_message][:receiver_id]
        user = User.find(params[:private_message][:receiver_id])
      else
        user = User.where(username: params[:receiver_name]).first
        receiver_id = user.id
      end
      
      if params[:private_message][:receiver_id].present? || user.present?
        if current_user.role.eql? user.role
          redirect_to private_messages_path, alert: "Sorry you cannot sent message to user with same role."
        else
          private_message = PrivateMessage.send_message(current_user, receiver_id, params, user)

          redirect_to private_messages_path, notice: "Your message has been sent"
        end
      else
        redirect_to private_messages_path, alert: "Sorry we can't find the username"
      end
    else
      redirect_to private_messages_path, alert: "Plase fill the message, Message cannot be blank"
    end
  end
  
  private

    def fetch_conversation_user
      @conversation_user = ConversationsUser.find(params[:conversations_user_id])
    end

    def fetch_private_message
      @private_message = PrivateMessage.find(params[:id])
    end

end

app/helpers/private_messages_helper.rb
module PrivateMessagesHelper
  def create_conversation(conversation, recepient, sender)
    conversation_user = ConversationsUser.create({ conversation_id: conversation, sender_id: current_user.id, receiver_id: recepient, is_deleted: false, is_read: true })
  end

  def is_conversation_not_deleted?(conversation)
  	con = conversation.private_messages.last.conversation.conversations_users.where(conversation_id: conversation.id, receiver_id: current_user.id).first
  	con && con.is_deleted.eql?(false)
  	# private_message = conversation.private_messages.where(receiver_id: current_user.id).first
    # private_message && private_message.is_deleted.eql?(false)
  end

end

app/views/private_messages/_form.html.slim
= form_for @private_message do |f|
  - if @private_message.errors.any?
    #error_explanation
      h2 = "#{pluralize(@private_message.errors.count, "error")} prohibited this private_message from being saved:"
      ul
        - @private_message.errors.full_messages.each do |message|
          li = message

  div style="font-size: 12px;"
    .col-md-3
      .field
        = f.number_field :sender_id, value: current_user.id, style: "display:none;"
      .field
        - if @recieved.present?
          = link_to "#{ @recieved.username }", show_sender_detail_path(user_id: @recieved.id)
          = text_field_tag :receiver_name, @recieved.username, readonly: true, style: "display: none;", class: "string optional form-control"
          = f.number_field :receiver_id, value: @recieved.id, style: "display:none;"
        - else
          = text_field_tag :receiver_name, '', placeholder: "To Username", id: "username", class: "string optional form-control"
          = f.number_field :receiver_id, style: "display:none;"
    .col-md-6
      .field
        = f.text_area :body, placeholder: "Enter Message", style: "width: 367px; height: 74px;", class: "text optional form-control"
      br/
      / .field
      / - if @file.eql?false
      / - else
      /   = check_box_tag :encrypted
      /   | &nbsp;
      /   | Information is sensitive, encrypt with PGP key (if receiver has one)
      / div id="show-pgp"
      /   .well
      /     - if @file.eql?true
      /       = "This user has a public PGP key"
      /     - elsif @key.present?
      /       = @key
      /     - else
      /       = "This user does not have a public key"
    .col-md-3
      .actions = f.submit 'Send Message', class: "btn btn-success"

app/views/private_messages/_show_pgp.html.slim
.well
  - if key.present?
    = key
  - else
    = "This user does not have a public key"

app/views/private_messages/_table_index.html.slim
table.table.table-bordered
  tr
    th From
    th
    th 
  - if @conversations.present?
    - @conversations.each do |conversation|
      - if is_conversation_not_deleted?(conversation) && conversation.private_messages.last.sender.present?
        tr
          td
            - if conversation.private_messages.last.receiver.username.eql? ( current_user.username )
              = link_to "#{ conversation.private_messages.last.sender.username }", show_sender_detail_path( user_id: conversation.private_messages.last.sender.id ), :"data-no-turbolink" => "true"
            - else
              = link_to "#{ conversation.private_messages.last.receiver.username }", show_sender_detail_path( user_id: conversation.private_messages.last.receiver.id ), :"data-no-turbolink" => "true"
          td
            - check_read = conversation.private_messages.last.conversation.conversations_users.where(conversation_id: conversation.id, receiver_id: current_user.id).first
            - if check_read.present?
              - if check_read.is_read.eql?false
                .new-box
                  = "new"
                - if conversation.private_messages.last.receiver.username.eql? ( current_user.username )
                  = link_to "#{ conversation.private_messages.last.body.gsub('<br/>', ' ') }", reply_path( user: conversation.private_messages.last.sender.username ), :"data-no-turbolink" => "true"
                - else
                  = link_to "#{ conversation.private_messages.last.body.gsub('<br/>', ' ') }", reply_path(user: conversation.private_messages.last.receiver.username), :"data-no-turbolink" => "true"
              - else
                - if conversation.private_messages.last.receiver.username.eql? ( current_user.username )
                  = link_to "#{ conversation.private_messages.last.body.gsub('<br/>', ' ') }", reply_path( user: conversation.private_messages.last.sender.username ), :"data-no-turbolink" => "true"
                - else
                  = link_to "#{ conversation.private_messages.last.body.gsub('<br/>', ' ') }", reply_path(user: conversation.private_messages.last.receiver.username), :"data-no-turbolink" => "true"
            - else
              = link_to "#{ conversation.private_messages.last.body.gsub('<br/>', ' ') }", reply_path(user: conversation.private_messages.last.receiver.username), :"data-no-turbolink" => "true"
          td
            - unless check_read.is_deleted
              = link_to "Delete entire thread", trash_path(conversations_user_id: check_read.id)
            | , &nbsp;
            - if check_read.is_read
              = link_to "Mark as Unread", unread_conversation_path(conversations_user_id: check_read.id)
            - else
              = link_to "Mark as read", read_conversation_path(conversations_user_id: check_read.id)
  - else
    tr 
      td colspan="4"
        | Your inbox is empty

app/views/private_messages/edit.html.slim
h1 Editing private_message

== render 'form'

= link_to 'Show', @private_message
'|
= link_to 'Back', private_messages_path

app/views/private_messages/index.html.slim
.clear-both
h4 My Messages

== render 'table_index'

app/views/private_messages/new.html.slim
h1 New private_message

== render 'form'

= link_to 'Back', private_messages_path

app/views/private_messages/reply.html.slim
h4 
  | Your Conversation with #{ link_to @user.username, show_sender_detail_path( user_id: @user.id) }

table.table.table-bordered
  tr
    th From
    th Message
    th
  = form_for @private_message do |f|
    tr
      td
      td
        = f.number_field :sender_id, value: current_user.id, style: "display:none;"
        = f.number_field :receiver_id, value: @recipient_id, style: "display:none;"
        = f.text_area :body, placeholder: "Enter Message", style: "width: 575px; height: 74px;", class: "text optional form-control"
      td
        .actions = f.submit 'Send Message', class: "btn btn-success"
  - @messages.each do |message|
    tr
      td
        - if message.sender.username.eql? current_user.username
          = "me"
        - else
          = link_to "#{message.sender.username}", show_sender_detail_path( user_id: message.sender.id)
        br/
        = distance_of_time_in_words(Time.now, message.created_at)
      td
        .well
          = message.body.html_safe
      td
        - if message.is_deleted.eql?false
          = link_to "Move to Trash", trash_private_message_path(id: message.id)
        - else
          = link_to "Move to Inbox", untrash_private_message_path(id: message.id)
        br/

app/views/private_messages/show.html.slim
p#notice = notice

p
  strong Sender:
  = @private_message.sender_id
p
  strong Receiver:
  = @private_message.receiver_id
p
  strong Body:
  = @private_message.body
p
  strong Status:
  = @private_message.status

= link_to 'Edit', edit_private_message_path(@private_message)
'|
= link_to 'Back', private_messages_path

app/views/private_messages/show_pgp.html.slim
.well
  | Inbox

- unless current_user.role.eql?"Support"
  h4 New
  == render 'form'

app/views/private_messages/show_pgp.js.erb
$("#show-pgp").html('<%=j render partial: "show_pgp", locals: { key: @key } %>');

app/views/private_messages/show_sender_detail.html.slim
b = @sender.username
br/
= "Description : #{@sender.description}"
br/
| Public Key
br/
- if @publickey.present?
  = text_area_tag :pgp_key, @publickey.gsub("<br/>","\n"), style: "height: 625px; width: 100%;", class: "text optional form-control"
- else
  = "Sorry this user not upload PGP public key"
br/
- if @sender.role.eql?"Vendor"
  = link_to "See All Item of Vendor", vendor_item_url(vendor_id: @sender.id)
| &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
= link_to "Send Message to #{@sender.username}", new_private_message_path(receiver_id: @sender.id), class: "btn btn-default"

app/views/private_messages/support_contact.html.slim
h4 Message to Support Team

= simple_form_for :message_support_contact, url: message_support_contact_path, :html => { :style => 'text-align: center;'} do |f|

  div style="font-size: 12px;"
    .col-md-3
      .field
        = f.number_field :sender_id, value: current_user.id, style: "display:none;"
      .field
        = text_field_tag :receiver_name, @support.username, readonly: true, class: "string optional form-control"
        = f.number_field :receiver_id, value: @support.id, style: "display:none;"
    .col-md-6
      .field
        = f.text_area :body, placeholder: "Enter Message", style: "width: 367px; height: 74px;", class: "text optional form-control"
      div id="show-pgp"
    .col-md-3
      .actions = f.submit 'Sent Message', class: "btn btn-success"

app/views/private_messages/trash.html.slim
h1 Trash
ul
- if @senders.present?
  - @senders.each do |sender|
    - unless sender.username.eql? current_user.username
      li
        = link_to "#{sender.username}", reply_path(sender_id: sender.id)
        | &nbsp; &nbsp; | &nbsp; &nbsp;
        = link_to "Untrash", untrash_path(sender_id: sender.id)
- else
  = "Your inbox is empty"
br/